# Fedora throughput-performance profile for the RG55G1.

[main]
summary=Broadly applicable tuning that provides excellent performance across a variety of common server workloads

[variables]
thunderx_cpuinfo_regex=CPU part\s+:\s+(0x0?516)|(0x0?af)|(0x0?a[0-3])|(0x0?b8)\b

[cpu]
governor=performance
energy_perf_bias=performance
min_perf_pct=100
energy_performance_preference=performance
boost=1

[acpi]
platform_profile=performance

[vm]
dirty_bytes = 40%
dirty_background_bytes = 10%

[vm.thunderx]
type=vm
uname_regex=aarch64
cpuinfo_regex=${thunderx_cpuinfo_regex}
transparent_hugepages=never

[sysctl]
#kernel.pid_max = 65536
vm.swappiness=180
net.core.somaxconn=>2048

[sysctl.thunderx]
type=sysctl
uname_regex=aarch64
cpuinfo_regex=${thunderx_cpuinfo_regex}
kernel.numa_balancing=0

[video]
panel_power_savings=0

