# NOTE: keep in sync with ../repart-p4-rootfs/40-rootfs.conf (a symlink
# breaks mkosi's sandbox staging of RepartDirectories, so this is a copy).
[Partition]
Type=root-arm64
UUID=693B9ABA-2FC7-4222-9BD9-D2DC7B82099A
Label=rootfs
SizeMinBytes=4.8G
Format=ext4
CopyFiles=/
GrowFileSystem=yes
