[Partition]
# systemd-boot, the BLS entries, kernels, initrds and the board DTB all live
# on the ESP; there is no separate XBOOTLDR partition.
Type=esp
UUID=7b52556b-8161-448e-a8bd-090266a93ac4
Label=EFI-SYSTEM
SizeMinBytes=1G
SizeMaxBytes=1G
Format=vfat
CopyFiles=/boot:/
CopyFiles=/efi:/
