[Distribution]
Distribution=fedora
Release=44
Architecture=arm64
Repositories=ultramarine

[Output]
Format=cpio
Output=ultramarine-trimui-bsp.initrd
OutputDirectory=../../../build
CompressOutput=gzip

[Content]
MakeInitrd=yes
Packages=
    systemd
    systemd-udev
    kmod
    util-linux
    e2fsprogs

[Build]
SandboxTrees=
    ../../../mkosi.sandbox/etc/dnf/dnf.conf:/etc/dnf/dnf.conf
    ../../../repodir/terra.repo:/etc/yum.repos.d/terra.repo
    ../../../repodir/ultramarine.repo:/etc/yum.repos.d/ultramarine.repo
CacheDirectory=../../../build/initrd-package-cache
